[build]
builder = "dockerfile"
dockerfilePath = "docker/backend.dockerfile"

[deploy]
startCommand = "./api"
healthcheckPath = "/api/v1/health"
healthcheckTimeout = 30
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 5
